# Generated by Django 3.1.6 on 2021-02-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='preview_format',
        ),
    ]
