# Generated by Django 3.1.6 on 2021-02-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_preview_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
    ]
