# Generated by Django 3.1.6 on 2021-02-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210209_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время мероприятия')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн подачи заявок')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('payment', models.CharField(max_length=100, verbose_name='Взнос')),
            ],
            options={
                'verbose_name': 'Анонс мероприятия',
                'verbose_name_plural': 'Анонсы мероприятий',
            },
        ),
    ]
