# Generated by Django 3.1.6 on 2021-02-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210209_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='payment',
            field=models.CharField(default='Отсутствует', max_length=100, verbose_name='Взнос'),
        ),
    ]
