# Generated by Django 3.1.6 on 2021-02-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210209_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='Нет информации', max_length=100, verbose_name='Организатор'),
        ),
    ]
