# Generated by Django 3.1.6 on 2021-02-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_photo_photoalbum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
    ]
