# Generated by Django 3.1.6 on 2021-02-09 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210209_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
