# Generated by Django 3.1.6 on 2021-02-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_questionanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'verbose_name': 'Вопрос-ответ', 'verbose_name_plural': 'Вопросы-ответы'},
        ),
    ]
