# Generated by Django 3.1.6 on 2021-02-21 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20210222_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
