# Generated by Django 3.1.7 on 2021-02-22 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_videolesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
