# Generated by Django 3.1.7 on 2021-02-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_videolesson_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='link',
            field=models.CharField(max_length=80, verbose_name='Ссылка на Youtube'),
        ),
    ]
