# Generated by Django 3.1.7 on 2021-02-23 06:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210223_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_page_text', tinymce.models.HTMLField(verbose_name='Текст на главной')),
                ('address', models.CharField(max_length=256, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('email', models.CharField(max_length=32, verbose_name='Email')),
                ('vk_link', models.CharField(max_length=32, verbose_name='Ссылка на ВК')),
                ('instagram_link', models.CharField(max_length=32, verbose_name='Ссылка на Instagram')),
            ],
            options={
                'verbose_name': 'Основная информация',
                'verbose_name_plural': 'Основная информация',
            },
        ),
    ]
