# Generated by Django 3.1.6 on 2021-02-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_maininformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininformation',
            name='instagram_link',
            field=models.CharField(max_length=80, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AlterField(
            model_name='maininformation',
            name='vk_link',
            field=models.CharField(max_length=80, verbose_name='Ссылка на ВК'),
        ),
    ]
