# Generated by Django 3.1.6 on 2021-02-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20210223_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininformation',
            name='youtube_link',
            field=models.CharField(max_length=80, null=True, verbose_name='Ссылка на YouTube'),
        ),
    ]
