# Generated by Django 3.1.6 on 2021-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_maininformation_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininformation',
            name='instagram_direct_link',
            field=models.CharField(max_length=80, null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='maininformation',
            name='vk_direct_link',
            field=models.CharField(max_length=80, null=True, verbose_name='Ссылка на ВК'),
        ),
    ]
