# Generated by Django 3.1.6 on 2021-02-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20210223_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maininformation',
            name='instagram_direct_link',
        ),
        migrations.AddField(
            model_name='maininformation',
            name='whatsapp_direct_link',
            field=models.CharField(max_length=80, null=True, verbose_name='Ссылка на переписку WhatsApp'),
        ),
        migrations.AlterField(
            model_name='maininformation',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Телефон (в формате 89..) без пробелов и скобок'),
        ),
        migrations.AlterField(
            model_name='maininformation',
            name='vk_direct_link',
            field=models.CharField(max_length=80, null=True, verbose_name='Ссылка на переписку ВК'),
        ),
    ]
