# Generated by Django 3.1.6 on 2021-02-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20210223_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininformation',
            name='whatsapp_direct_link',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Ссылка на переписку WhatsApp'),
        ),
    ]
