# Generated by Django 3.1.6 on 2021-02-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20210223_1738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoLesson',
            new_name='Video',
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео с Youtube', 'verbose_name_plural': 'Видео с YouTube'},
        ),
    ]
